FROM mcr.microsoft.com/dotnet/sdk:9.0-preview AS ef-migrator

WORKDIR /app

COPY . .

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

RUN dotnet restore

CMD ["dotnet", "ef", "database", "update", "--project", "/app/StevenSoftware.Server.csproj"]
