FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
RUN apt-get update && apt-get install -y git
ARG REPO_URL=https://github.com/lordstimpa/StevenSoftware.git
RUN git clone $REPO_URL . && cd stevensoftware.Server

RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 80
ENTRYPOINT ["dotnet", "StevenSoftware.Server.dll"]